---
- name: Install Flask, Nginx, and Mongodb
  hosts: all
  user: root
  vars_files:
   - vars.yml
  roles:
    - common


- name: Install Enferno Project
  vars_files:
   - vars.yml
  hosts: all
  remote_user: root
  sudo: true
  sudo_user: "{{user_name}}"
  roles:
    - enferno



